# -*- coding: utf-8 -*-
"""correl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F705972Qcok1ywq1sxSOsxY-NvTtNHCA
"""

import pandas as pd
df = pd.read_csv('data.csv')
df2 = pd.read_csv('data2.csv')

df = df[['Data','Último']]
df2 = df2[['Data','Último']]

df = pd.merge(df, df2, on='Data', how='inner')
df['Data'] = pd.to_datetime(df['Data'], format='%d.%m.%Y')

df = df.sort_values(by='Data')
for coluna in ['Último_x', 'Último_y']:
    df[coluna] = df[coluna].str.replace(',', '.', regex=True)  # Remove os pontos (separadores de milhar)
    df[coluna] = df[coluna].str.replace(',', '.', regex=True)  # Substitui vírgulas por pontos
    df[coluna] = pd.to_numeric(df[coluna])

df

df['Último_x'] = df['Último_x'].pct_change()
df['Último_y'] = df['Último_y'].pct_change()

df

df = df.dropna()

correlacao = df['Último_x'].corr(df['Último_y'])
print(f"Correlação entre os retornos das empresas: {correlacao:.4f}")