# -*- coding: utf-8 -*-
"""RUBY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVUr7T5rYlcYjYul3Bt1GybZ9dlbsMsZ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Carregar os dados do arquivo CSV
df = pd.read_excel('ebit.xlsx', index_col='TICKER')

c = ['PRECO','EV/EBIT','ROIC','VALOR DE MERCADO', 'LIQUIDEZ MEDIA DIARIA']

df = df[c]
df = df.dropna()
df

df = df[df['PRECO'] != 0]


df = df[df['EV/EBIT'] > 0]
df = df[df['LIQUIDEZ MEDIA DIARIA'] > 3_000_000]
df = df[df['ROIC'] > 0]

df

df_V = df.drop(columns=df.columns.difference(['VALOR DE MERCADO']))
print(df_V)

df_roic = df.sort_values(by='ROIC', ascending=False)
df_roic = df_roic.drop(columns=df_roic.columns.difference(['ROIC']))
df_roic['PONTOS R'] = range(1, 147)
df_roic

# Selecionar as colunas desejadas e adicionar 'PONTOS E'
df_EY = df.drop(columns=df.columns.difference(['EV/EBIT']))
df_E = (1/df_EY['EV/EBIT']) * 100
df_EY['EV/EBIT'] = df_E

# Ordenar o DataFrame com base na coluna 'LPA/PRECO' em ordem decrescente
df_EY = df_EY.sort_values(by='EV/EBIT', ascending=False)
df_EY['PONTOS E'] = range(1, 147)
# Exibir o DataFrame

print(df_E)
df_EY

df_combined = df_roic.join(df_EY)
df_combined['Soma'] = df_combined['PONTOS E'] + df_combined['PONTOS R']
df_combined.sort_values(by='Soma', ascending=False)
df_combined = df_combined.join(df_V)
df_combined = df_combined.sort_values(by='Soma', ascending=True)
df_combined = df_combined[df_combined['VALOR DE MERCADO'] > 500_000_000]
df_combined

df_combined.to_excel('resultado.xlsx', index=False)